version: 2

sources:
  - name: exemple_big_query
    schema: exemple_big_query
    tables:
      - name: event_flattened
      - name:  table_big_query
      
  - name: google_sheet
    schema: google_sheet
    tables:
      - name: manager_regions

  - name: dataset_fil_rouge
    schema: dataset_fil_rouge
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user